/**
 * Style Dictionary Configuration
 *
 * Transforms Figma token exports (W3C DTCG format) into:
 *   - CSS custom properties
 *   - SCSS variables
 *   - Android XML resources
 *   - iOS Swift constants
 *   - TypeScript/JavaScript modules
 *
 * Token source format: W3C Design Token Community Group (DTCG)
 * Docs: https://tr.designtokens.org/format/
 *
 * Usage:
 *   npm run build:tokens         — build all platforms once
 *   npm run build:tokens:watch   — rebuild on token file changes
 */

import StyleDictionary from 'style-dictionary';

// ─── Type filter helpers ──────────────────────────────────────────────────────
const isColor     = (token) => token.type === 'color';
const isDimension = (token) => token.type === 'dimension';

// ─── Register custom transforms ──────────────────────────────────────────────

/**
 * name/camelCase — Converts token path to camelCase for TypeScript/JS output.
 * Example: color.blue.500 → colorBlue500
 */
StyleDictionary.registerTransform({
  name: 'name/camelCase',
  type: 'name',
  transform: (token) => {
    return token.path
      .map((part, i) => {
        // Strip non-alphanumeric chars (handles keys like "2xl", "0.5")
        const clean = part.replace(/[^a-zA-Z0-9]/g, '');
        if (i === 0) return clean.toLowerCase();
        return clean.charAt(0).toUpperCase() + clean.slice(1).toLowerCase();
      })
      .join('');
  },
});

// ─── Register custom formats ──────────────────────────────────────────────────

/**
 * typescript/module — Generates a typed TypeScript file with named exports.
 * Example: export const colorBlue500 = "#3b82f6";
 */
StyleDictionary.registerFormat({
  name: 'typescript/module',
  format: ({ dictionary }) => {
    const header = [
      '/**',
      ' * Design Tokens — TypeScript Module',
      ' * Auto-generated by Style Dictionary. Do not edit directly.',
      ' * Source: tokens/**/*.json',
      ' *',
      ` * Generated: ${new Date().toISOString()}`,
      ' */',
      '',
    ].join('\n');

    const exports = dictionary.allTokens
      .map((token) => {
        const val = JSON.stringify(token.value);
        const comment = token.comment ? ` // ${token.comment}` : '';
        return `export const ${token.name} = ${val} as const;${comment}`;
      })
      .join('\n');

    // Build a nested object for convenience
    const nested = buildNestedObject(dictionary.allTokens);
    const nestedStr = JSON.stringify(nested, null, 2)
      .replace(/"([^"]+)":/g, '$1:') // unquote keys
      .replace(/"/g, "'");           // single quotes

    return [
      header,
      '// ─── Named exports (tree-shaking friendly) ──────────────────────────────────',
      exports,
      '',
      '// ─── Nested object (full token map) ─────────────────────────────────────────',
      `export const tokens = ${nestedStr} as const;`,
      '',
      'export type TokenValue = string | number;',
      'export type Tokens = typeof tokens;',
      '',
    ].join('\n');
  },
});

/** Builds a nested object from flat token list for the `tokens` export. */
function buildNestedObject(allTokens) {
  const result = {};
  for (const token of allTokens) {
    let cursor = result;
    for (let i = 0; i < token.path.length - 1; i++) {
      const key = token.path[i];
      if (!cursor[key]) cursor[key] = {};
      cursor = cursor[key];
    }
    cursor[token.path[token.path.length - 1]] = token.value;
  }
  return result;
}

// ─── Style Dictionary configuration ──────────────────────────────────────────

const sd = new StyleDictionary({
  /**
   * Token source files — matches all JSON files in the tokens/ directory.
   * Figma plugins (Tokens Studio, Variables) export to this directory.
   */
  source: ['tokens/**/*.json'],

  /**
   * Enable W3C DTCG format support.
   * This tells Style Dictionary to expect $value and $type in token files.
   * Compatible with: Figma Variables export, Tokens Studio, W3C DTCG spec.
   */
  usesDtcg: true,

  platforms: {
    // ── CSS Custom Properties ─────────────────────────────────────────────────
    css: {
      transformGroup: 'css',
      buildPath: 'dist/css/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            /**
             * outputReferences: true means semantic tokens will reference
             * primitive tokens using CSS var() — great for runtime theming.
             * Example: --semantic-color-text-primary: var(--color-gray-900);
             */
            outputReferences: true,
            selector: ':root',
          },
        },
      ],
    },

    // ── SCSS Variables ────────────────────────────────────────────────────────
    scss: {
      transformGroup: 'scss',
      buildPath: 'dist/scss/',
      files: [
        {
          destination: '_variables.scss',
          format: 'scss/variables',
          options: {
            outputReferences: true,
          },
        },
        {
          destination: '_map.scss',
          format: 'scss/map-deep',
          mapName: 'tokens',
        },
      ],
    },

    // ── Android XML Resources ─────────────────────────────────────────────────
    android: {
      transformGroup: 'android',
      buildPath: 'dist/android/',
      files: [
        {
          /**
           * colors.xml — Android color resources.
           * Usage: @color/color_blue_500 (XML) or R.color.color_blue_500 (Kotlin)
           */
          destination: 'colors.xml',
          format: 'android/colors',
          filter: isColor,
        },
        {
          /**
           * dimens.xml — Android dimension resources (dp/sp).
           * Usage: @dimen/spacing_4 (XML) or resources.getDimension(R.dimen.spacing_4)
           */
          destination: 'dimens.xml',
          format: 'android/dimens',
          filter: isDimension,
        },
      ],
    },

    // ── iOS Swift ─────────────────────────────────────────────────────────────
    ios: {
      transformGroup: 'ios-swift',
      buildPath: 'dist/ios/',
      files: [
        {
          /**
           * StyleDictionaryColor.swift — UIColor constants for iOS.
           * Usage: StyleDictionaryColor.colorBlue500
           */
          destination: 'StyleDictionaryColor.swift',
          format: 'ios-swift/class.swift',
          className: 'StyleDictionaryColor',
          filter: isColor,
        },
        {
          /**
           * StyleDictionarySize.swift — CGFloat dimension constants.
           * Usage: StyleDictionarySize.spacingFour
           */
          destination: 'StyleDictionarySize.swift',
          format: 'ios-swift/class.swift',
          className: 'StyleDictionarySize',
          filter: isDimension,
        },
      ],
    },

    // ── TypeScript / JavaScript ───────────────────────────────────────────────
    typescript: {
      transforms: ['attribute/cti', 'name/camelCase', 'color/hex', 'size/rem'],
      buildPath: 'dist/ts/',
      files: [
        {
          /**
           * tokens.ts — Named exports + nested object.
           * Usage: import { colorBlue500 } from './tokens';
           *        import { tokens } from './tokens'; tokens.color.blue['500']
           */
          destination: 'tokens.ts',
          format: 'typescript/module',
        },
      ],
    },
  },
});

// ─── Run build ────────────────────────────────────────────────────────────────
try {
  await sd.buildAllPlatforms();
  console.log('\n✅ Design tokens built successfully!\n');
  console.log('  Outputs:');
  console.log('  ├── dist/css/variables.css');
  console.log('  ├── dist/scss/_variables.scss');
  console.log('  ├── dist/scss/_map.scss');
  console.log('  ├── dist/android/colors.xml');
  console.log('  ├── dist/android/dimens.xml');
  console.log('  ├── dist/ios/StyleDictionaryColor.swift');
  console.log('  ├── dist/ios/StyleDictionarySize.swift');
  console.log('  └── dist/ts/tokens.ts\n');
} catch (err) {
  console.error('\n❌ Build failed:', err.message);
  process.exit(1);
}
